#!/system/bin/sh

# Busybox 
if [ -e /su/xbin/busybox ]; then
	BB=/su/xbin/busybox;
else if [ -e /sbin/busybox ]; then
	BB=/sbin/busybox;
else
	BB=/system/xbin/busybox;
fi;
fi;

CONFIG_JSON=/res/synapse/config.json;
ACTION_SCRIPTS=/res/synapse/actions/;

if [ ! -f $CONFIG_JSON ]; then
	source /res/synapse/json.generate > $CONFIG_JSON;
fi

case "${1}" in

  config)
	cat $CONFIG_JSON;
  ;;

  configpath)
	echo $CONFIG_JSON;
  ;;

  actionpath)
	echo $ACTION_SCRIPTS:/sbin;
  ;;

  reset)
	$BB mount -t rootfs -o rw,remount rootfs;
	$BB rm -f $CONFIG_JSON;
	$BB mount -t rootfs -o rw,remount rootfs;
  ;;

esac;
